dataset:
  root: "/kaggle/input/flowers-recognition/flowers"
  image_size: 224
  num_workers: 2
splits:
  train_ratio: 0.8
training:
  batch_size: 32
  epochs: 15
  lr_backbone: 1e-4
  lr_head: 1e-3
index:
  ...
models:
  - resnet50
  - efficientnet_b0
  - clip_zeroshot
  - clip_finetune
  - metric_learning
seed: 42
