version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    command: python3 -m app.main
    
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    command: streamlit run improved_streamlit.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api

